name: Build and Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t your-image-name .

      - name: Stop Existing Container (optional)
        run: docker stop my-streamlit-app || true

      - name: Remove Existing Container (optional)
        run: docker rm my-streamlit-app || true

      - name: Run Docker Container
        run: |
          echo "$GROQ_API_KEY" > secrets.toml 
          docker run -d -p 8501:8501 --name my-streamlit-app -v $(pwd)/secrets.toml:/root/.streamlit/secrets.toml -e GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} my-streamlit-app
